apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jsachdev07/mynode:v1
          env:
          - name: MONGO_CONN_STR
            value: "mongodb://mongodb:27017/todo?directConnection=true"
          - name: MONGO_USERNAME
            value: "root"
          
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: shared-volume
            mountPath: /app/shared-data
          volumes:
          - name: shared-volume
            persistentVolumeClaim:
              claimName: shared-exchange-pvc
