apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqls
  labels:
    app: mysqls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqls
  template:
    metadata:
      labels:
        app: mysqls
    spec:
      containers:
      - image: mysql:5.6
        name: mysqls
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: myapp_db
        - name: MYSQL_USER
          value: appuser
        - name: MYSQL_PASSWORD
          value: app123        
        ports:
        - containerPort: 3306
          name: mysqls
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim		  
